FROM ghcr.io/va7eex/rtl433:base

ENV MQTT_IP=mqtt-broker \
    MQTT_PORT=1883 \
    #can be 'si', 'customary', or 'native'
    UNITS=si \
    TZ=Etc/UTC \
    #device index, in the event there are multiple SDRs plugged in
    DEVICEINDEX=0

COPY entrypoint.sh /usr/share

ENTRYPOINT /usr/share/entrypoint.sh

#ENTRYPOINT rtl_433 -M newmodel -F mqtt://$MQTT_IP:$MQTT_PORT,retain=0,devices=sensors/rtl_433/[model:""]/[id:0] -C $UNITS
