FROM va7eex/rtl433:latest

ENV MQTT_IP=mqtt-broker

ENV MQTT_PORT=1883

#can be 'si', 'customary', or 'native'
ENV UNITS=si
ENV TZ=Etc/UTC

COPY entrypoint.sh /usr/share

ENTRYPOINT /usr/share/entrypoint.sh

#ENTRYPOINT rtl_433 -M newmodel -F mqtt://$MQTT_IP:$MQTT_PORT,retain=0,devices=sensors/rtl_433/[model:""]/[id:0] -C $UNITS
